version: "3"

networks:
  discord:
    driver: bridge
 
services:
  bot:
    restart: always
    build: .
    volumes:
      - ".:/home"
      - "/home/node_modules"
    env_file:
      - .env
      - .env.mysql
    networks:
      - discord
  mysql:
    restart: always
    image: mariadb:10.5
    env_file:
      - .env.mysql
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      discord:
        aliases:
          - "mysql"
  phpmyadmin:
    restart: always
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=8192M
    ports:
      - "8181:80"
    networks:
      - discord
  redis:
    image: redis:6-alpine
    restart: always
    networks:
        discord:
          aliases:
            - "redis"
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - discord
    ports:
      - 8081:8081